export const mockJson  = {
        "Dettaglio":"",
        "Entity": "string",
        "Isin": "string",
        "InstrumentName": "string",
        "MaturityDate": "string",
        "IssuerName": "string",
        "IssuerCode": 0,
        "Currency": "string",
        "MarketCode": "string",
        "AgentName": "string",
        "SettledQty": 0,
        "LatestCleanPrice": 0,
        "LatestDirtyPrice": 0,
        "PriceSource": "string",
        "SettledValue": 0,
        "BVALScore": 0,
        "EligibileBCE": true,
        "EligibileFED": true,
        "EligibileHKM": true,
        "EligibileBOE": true,
        "Marketability": "string",
        "LiquidityClass": "string",
        "LiquidityClassHaircut": 0,
        "LiquidityClassStressHaircut": 0,
        "LiquidityClassPolicyHaircut": 0,
        "LiquidityTypeName": "string",
        "SecurityTypeName": "string",
        "BBGLiquidityClassDate": "string",
        "BBGLiquidityClass": "string",
        "LRSNarrative": "string",
        "BloombergCode": "string"
}
